package com.myproject.hello.entity;
// Generated 2018-8-26 11:50:53 by Hibernate Tools 3.5.0.Final

/**
 * UserT generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String userName;
	private String password;
	private int age;

	public User() {
	}

	public User(String userName, String password, int age) {
		this.userName = userName;
		this.password = password;
		this.age = age;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

}
